### ISSUE TITLE
Rendering multiple view mode selectors in form

### ISSUE THREAD

**Issue by vegas12** [drupal-fancy/view_mode_selector#25]
Causing fatal error such as "function sortByRegionCount already declared".

Suggesting that we wrap function declaration in function_exists.

**Comment by yannickoo** [comment]
Oh, this has been fixed for `7.x-1.x` [#3] but not for `8.x-1.x` 🤐 

Thank you for the hint!

**Comment by vegas12** [comment]
No problem! :)

It seems like the version I can download from drupal.org does not yet have the change.
Seems to be only in dev version.

**Comment by fmuellerprevion** [comment]
Because the stable version on the Drupal Project page is still not having the commit, you may use the attached patch file to apply the exact commited changes to your module until the dev version gets into stable .(Rename the file from .txt to .patch and apply it using PhpStorm or whatever you're using).

[sortByRegionCount_function_already_defined.txt](https://github.com/drupal-fancy/view_mode_selector/files/2197812/sortByRegionCount_function_already_defined.txt)
