### ISSUE TITLE
Relation

### ISSUE THREAD

**Issue by funkytraffic** [drupal-fancy/view_mode_selector#4]
I would like to use this module for a field of the relation module.
http://drupal.org/project/relation

Therefore I need to pick the view modes of the target entity and not of the relation.

**Comment by axe312ger** [comment]
You can try to use the field etc. from the view_mode_selector module and implement your own hook_entity_view_mode_alter() to set the your desired view mode.

Our implementation might help you:
https://github.com/drupal-fancy/view_mode_selector/blob/7.x-1.x/view_mode_selector.module#L321-L356

Otherwise, we might implement a hook to alter the chosen view mode. @yannickoo what do you think?

**Comment by funkytraffic** [comment]
Background is, I want to use relations like entity reference selector.
https://www.drupal.org/project/er_viewmode

But I guess it is to complicated in practice.

**Comment by yannickoo** [comment]
It would be great to have this for entity reference fields but there is also [Paragraph View Mode](https://www.drupal.org/project/paragraph_view_mode) :)
