### ISSUE TITLE
Cannot redeclare function error

### ISSUE THREAD

**Issue by sejancich** [drupal-fancy/view_mode_selector#8]
When trying to add a new paragraphs entity to a node, I was getting an error about sortByRegionCount() being redeclared (line 189 of view_mode_selector.module). I think you need to move this function outside of view_mode_selector_view_modes(). You might also consider name spacing the function once moved to prevent collisions.

**Comment by yannickoo** [comment]
Please use the latest version of View Mode Selector. This has been already fixed - see #3.

**Comment by fmuellerprevion** [comment]
Because the stable version on the Drupal Project page is still not having the commit, you may use the attached patch file to apply the exact commited changes to your module until the dev version gets into stable .(Rename the file from .txt to .patch and apply it using PhpStorm or whatever you're using).

[sortByRegionCount_function_already_defined.txt](https://github.com/drupal-fancy/view_mode_selector/files/2197811/sortByRegionCount_function_already_defined.txt)
